#!/usr/bin/perl -w
use strict;

# Make a pattern that will match three consecutive copies of whatever is currently contained
# in $what.  That is, if $what is 'fred', your pattern should match 'fredfred'. If $what is
# 'fred|barney', your pattern should match 'fredfredbarney' or 'barneyfredfred' or 'barneybarneybarney'

/($what){3}/