#!/usr/bin/perl -w
use strict;
use 5.010;

say "Enter column width and then list of strings: ";
chomp(my @strings = <STDIN>);
my $width = shift @strings;

# Print ruler line
print "1234567890" x 7, "12345\n";

# Don't forget to use `printf` not `print`
printf "%${width}s\n" x @strings, @strings;