#!/usr/bin/perl -w
use 5.010;
use strict;

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";

sub get_average {
    if (@_ == 0) { return }
    my $total = 0;
    my $len = @_;

    foreach my $num (@_) {
        $total += $num;
    }
    $total/$len
}

sub above_average {
    my $average = &get_average(@_);
    my @above_avg;

    foreach my $num (@_) {
        if ($num > $average) {
            push @above_avg, $num;
        }
    }
    @above_avg
}