#!/usr/bin/perl -w
use 5.010;
use strict;

my @fred = qw(1 3 5 7 9);
my $fred_total = total(@fred);

print "The total of \@fred is $fred_total.\n";
print "Enter some numbers on seperate lines: ";

my $user_total = total(<STDIN>);
print "The total of those numbers is $user_total.\n";

print "The total sum from 1 to 1000 is ", total(1..1000), "\n";

sub total {
    my $sum; # Not necessary to do `my $sum = 0`
    foreach my $num (@_) {
        $sum += $num;
    }
    $sum;
}