#!/usr/bin/perl -w
use 5.010;

# 2. Write a program that reads a list of numbers (on seperate lines) until 
#    end of input and then prints for each number the corresponding person's
#    name from the list below.  
my @names = qw(fred betty dino wilma pebbles bamm-bamm);
print "Enter numbers from 0 to ", scalar @names - 1, "\n";
my @list_of_nums = <STDIN>;

foreach $num (@list_of_nums) {
    print $names[$num], "\n";
}