#!/usr/bin/perl -w
use strict;
use 5.010;

$ENV{ZERO} = 0;
$ENV{EMPTY} = '';
$ENV{UNDEFINED} = undef;

while (my($key, $value) = each %ENV) {
    $value = $value // '(undefined value)';
    print "$key => $value\n";
}
